# Generated by Django 4.2.5 on 2023-10-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InputHistory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputorder",
            name="specialNotes",
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
