# Generated by Django 4.2.5 on 2023-10-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("InputHistory", "0002_inputorder_specialnotes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inputorderitem", old_name="outputOrder", new_name="inputOrder",
        ),
    ]
