# Generated by Django 4.2.5 on 2023-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InputHistory', '0003_rename_outputorder_inputorderitem_inputorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputorder',
            name='isExternal',
            field=models.BooleanField(default=False),
        ),
    ]
