# Generated by Django 4.2.7 on 2023-12-05 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InputHistory', '0004_inputorder_isexternal'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputorderitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
