# Generated by Django 4.2.5 on 2023-10-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Workers", "0003_alter_worker_employeenumber"),
        ("Product", "0005_alter_historicalproduct_sku_alter_product_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutputOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Workers.worker"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutputOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "outputOrder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OutputHistory.outputorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.product",
                    ),
                ),
            ],
        ),
    ]
