# Generated by Django 4.2.6 on 2023-10-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OutputHistory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker", name="workerCode", field=models.PositiveIntegerField(),
        ),
    ]
