# Generated by Django 4.2.6 on 2023-10-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OutputHistory", "0002_alter_worker_workercode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outputorder", old_name="workerCode", new_name="worker",
        ),
    ]
