# Generated by Django 4.2.5 on 2023-10-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Workers", "0001_initial"),
        ("OutputHistory", "0003_rename_workercode_outputorder_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outputorder",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Workers.worker"
            ),
        ),
        migrations.DeleteModel(name="Worker",),
    ]
