# Generated by Django 4.2.5 on 2023-10-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_outputorder_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputorderitem',
            name='outputOrder',
        ),
        migrations.RemoveField(
            model_name='outputorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='OutputOrder',
        ),
        migrations.DeleteModel(
            name='OutputOrderItem',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
