# Generated by Django 4.2.5 on 2023-10-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0004_remove_outputorderitem_outputorder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="SKU",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="SKU",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
