# Generated by Django 4.2.5 on 2023-10-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("employeeNumber", models.IntegerField(max_length=255)),
                ("workArea", models.CharField(max_length=255)),
            ],
        ),
    ]
