# Generated by Django 4.2.5 on 2023-10-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Workers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker", name="employeeNumber", field=models.IntegerField(),
        ),
    ]
