# Generated by Django 4.2.5 on 2023-10-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Workers", "0002_alter_worker_employeenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="employeeNumber",
            field=models.IntegerField(unique=True),
        ),
    ]
